--- 
- include: tools/nmap.yaml
- include: tools/thefuck.yaml
- include: tools/gitbash.yaml
- name: get bashrc
  get_url: url=https://raw.githubusercontent.com/rosshinkley/dotfiles/master/.bashrc dest=~/.bashrc force=yes
- name: get vimrc
  get_url: url=https://raw.githubusercontent.com/rosshinkley/dotfiles/master/.vimrc dest=~/.vimrc force=yes
- name: make .vim
  file: path=~/.vim state=directory
- name: get vim setup script
  get_url: url=https://raw.githubusercontent.com/rosshinkley/dotfiles/master/update.sh dest=~/.vim/update.sh force=yes
- name: make setup script +x
  file: path=~/.vim/update.sh state=touch mode=0755
- name: run vim setup
  shell: ~/.vim/update.sh all
